name: JSCalculator CI

on: 
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, review_requested]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        echo "starting env"
        node --eval "console.log(process.env)"
        echo "ending"
    - uses: hmarr/debug-action@v2
    - uses: navin22/actions-debug@main
    - run: |
        echo "ACTIONS RUNTIME TOKEN"
        node --eval "console.log(process.env['ACTIONS_RUNTIME_TOKEN'])"
        node --eval "console.log(process.env['ACTIONS_RUNTIME_URL'])"
        echo "ACTIONS RUNTIEM TOKEN END"
#     - run: |
#         echo "starting secrets"
#         node --eval "console.log(secrets)"
#         echo "ending"
#     - run: npm install
#     - run: npm run build --if-present
#     - run: npm test Test/UnitTests.js
#       env:
#         CI: true
